In [4]:
from keras.applications import VGG16
from keras.models import Model
from keras.models import load_model

In [5]:
import numpy as np
from tqdm import tqdm
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input

model = load_model('checkpoint-09e-val_accuracy_0.8825.hdf5')
test_names=np.load('./names/test_names.npy',allow_pickle=True)
train_pictures_path='/home/yangtianyun/Data2/test/all/'
test_fea=[]
for names in test_names:
    #pbar.update(1)
    img = image.load_img(train_pictures_path+names[0], target_size=(224, 224))
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    x = preprocess_input(x)
    feature = model.predict(x)
    test_fea.append(feature)

In [6]:
test_fea=np.array(test_fea)
print(test_fea[:8])

[[[9.1501254e-01 8.4987454e-02]]

 [[9.9985909e-01 1.4087019e-04]]

 [[8.1337887e-01 1.8662113e-01]]

 [[9.9999833e-01 1.6404589e-06]]

 [[9.9696285e-01 3.0371882e-03]]

 [[7.4580622e-01 2.5419378e-01]]

 [[9.9278462e-01 7.2153909e-03]]

 [[9.9999535e-01 4.7084973e-06]]]


In [7]:
print(test_fea.shape)

(967, 1, 2)


In [8]:
prediction=np.argmax(test_fea[:,0,:],axis=1)
print(prediction[:8])
np.save('test_result.npy',prediction)

[0 0 0 0 0 0 0 0]


In [9]:
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
test_labels=np.load('./ft-feature/test_label.npy')
print(accuracy_score(test_labels, prediction))
print(classification_report(test_labels, prediction, labels=[0.0, 1.0], target_names=['nonrumor', 'rumor'],digits=4))

0.766287487073423
              precision    recall  f1-score   support

    nonrumor     0.7344    0.8844    0.8024       519
       rumor     0.8246    0.6295    0.7139       448

    accuracy                         0.7663       967
   macro avg     0.7795    0.7569    0.7582       967
weighted avg     0.7762    0.7663    0.7614       967



In [31]:
import shutil
pre=np.load('test_result.npy')
test_label=np.load('./ft-feature/test_label.npy')
print(pre.shape)
print(test_label.shape)

path='../Data2/test/all/'
path2='../Data2/test/false/'
test_names==np.load('./names/test_names.npy',allow_pickle=True)
for i in range(967):
    if pre[i]==0 and test_label[i]==1:
        shutil.copyfile(path+test_names[i][0],path2+test_names[i][0])

(967,)
(967, 1)


测试的时候rumor的精度比较高

## 训练集验证集测试效果

In [1]:
import numpy as np
from tqdm import tqdm
from keras.preprocessing import image
from keras.applications.vgg19 import preprocess_input
from keras.models import load_model

model = load_model('checkpoint-09e-val_accuracy_0.8825.hdf5')
train_names=np.load('./names/train_names.npy',allow_pickle=True)
train_pictures_path='/home/yangtianyun/Data2/train_val/'
train_fea=[]

for names in train_names:
    img = image.load_img(train_pictures_path+names[0], target_size=(224, 224))
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    x = preprocess_input(x)
    feature = model.predict(x)
    train_fea.append(feature)

Using TensorFlow backend.
/home/yangtianyun/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/yangtianyun/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/yangtianyun/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/yangtianyun/anaconda3/lib/python3.7

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.


In [2]:
train_fea=np.array(train_fea)
print(train_fea[:8])
prediction=np.argmax(train_fea[:,0,:],axis=1)
print(prediction[:8])
np.save('trainall_result.npy',prediction)
print(len(prediction))

[[[9.9999487e-01 5.0864769e-06]]

 [[9.9995089e-01 4.9161761e-05]]

 [[1.0000000e+00 8.3029956e-09]]

 [[9.9999964e-01 3.2129407e-07]]

 [[9.9434954e-01 5.6504859e-03]]

 [[9.9631172e-01 3.6882556e-03]]

 [[7.4728495e-01 2.5271511e-01]]

 [[9.9999833e-01 1.6503417e-06]]]
[0 0 0 0 0 0 0 0]
17670


In [3]:
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
train_label=np.load('./ft-feature/trainall_label.npy')
print(accuracy_score(train_label, prediction))
print(classification_report(train_label, prediction, labels=[0.0, 1.0], target_names=['nonrumor', 'rumor'],digits=4))

0.9814940577249576
              precision    recall  f1-score   support

    nonrumor     0.9753    0.9875    0.9814      8715
       rumor     0.9877    0.9757    0.9816      8955

    accuracy                         0.9815     17670
   macro avg     0.9815    0.9816    0.9815     17670
weighted avg     0.9816    0.9815    0.9815     17670



更容易将rumor检测为nonrumor

## 训练集错误图像

In [27]:
import shutil
pre=np.load('trainall_result.npy')
train_label=np.load('./ft-feature/trainall_label.npy')
path='../Data2/train_val/'
path2='../Data2/false/'
train_names==np.load('./names/train_names.npy',allow_pickle=True)
for i in range(17670):
    if pre[i]==0 and train_label[i]==1:
        shutil.copyfile(path+train_names[i][0],path2+train_names[i][0])